name: l10n_cli
description: A sample command-line application.
# version: 1.0.0
# author: Rami Abou Ghanem <raboughanem@google.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: 1.8.0
  test: ^1.0.0
