name: codeviewer_cli
description: A command-line application to highlight dart source code.

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  string_scanner: 1.0.5

dev_dependencies:
  pedantic: 1.8.0
  test: ^1.5.0
